version: "3.7"
services:
  db1:
    container_name: db1
    image: "mysql:8"
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: pjsavdb
      MYSQL_ROOT_PASSWORD: password
    networks:
      - backend
  repas_app:
    build: .
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db1:3306/pjsavdb?createDatabaseIfNotExists=true&allowPublicKeyRetrieval=true&useSSL=false&enabledTLSProtocols=TLSv1.2
      SPRING_DATASOURCE_USERNAME: hamadi
      SPRING_DATASOURCE_PASSWORD: madi95
    networks:
      - backend
    depends_on:
      - db1
    command: java -jar /mlr-it-consulting-repas-app.jar
    #sh -c './wait-for docker-mysql:3306 -- npm start'
networks:
  backend:
    external: true