# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: setup-mysql
      uses: shogo82148/actions-setup-mysql@v1.7.0
      with:
        mysql-version: '5.7'
        my-cnf: |
          innodb_log_file_size=256MB
          innodb_buffer_pool_size=512MB
          max_allowed_packet=16MB
          max_connections=50
          local_infile=1
    - run: sudo mysql -h 127.0.0.1 -u root -e 'SELECT version()'
    
      #run: |
      #  sudo /etc/init.d/mysql start
      #  mysql -h 127.0.0.1 -u root -proot -e 'CREATE DATABASE test_db;'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Display structure of downloaded files
      run: ls -R

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: surefire-reports
        path: target/surefire-reports/** # or path/to/artifact

    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
    

